-- DDL for SETTLE_BKLV table (Bakong Large Value fund transfer records)
-- Run this against the SIS Oracle database before deploying the new endpoint.

CREATE TABLE SETTLE_BKLV (
    SETTLE_BKLV_ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    SYSTEM_ID               NUMBER NOT NULL
        CONSTRAINT FK_SETTLE_BKLV_SYSTEM REFERENCES SYSTEM(SYSTEM_ID),
    EXT_REF                 VARCHAR2(100) NOT NULL,
    SOURCE_BANK             VARCHAR2(100) NOT NULL,
    DESTINATION_BANK        VARCHAR2(100) NOT NULL,
    DEBIT_ACCOUNT           VARCHAR2(50)  NOT NULL,
    AMOUNT                  NUMBER(18,2)  NOT NULL,
    CURRENCY                VARCHAR2(10)  NOT NULL,
    ISO_MESSAGE             CLOB,
    SETTLEMENT_STATUS_ID    NUMBER NOT NULL
        CONSTRAINT FK_SETTLE_BKLV_STATUS REFERENCES STATUS(STATUS_ID),
    BKLV_REQUEST_CONTENT    CLOB,
    BKLV_RESPONSE_CONTENT   CLOB,
    BKLV_RESPONSE_STATUS_ID NUMBER
        CONSTRAINT FK_SETTLE_BKLV_RESP_STATUS REFERENCES STATUS(STATUS_ID),
    BKLV_RESPONSE_AT        TIMESTAMP,
    BKLV_REFERENCE          VARCHAR2(200),
    CREATED_AT              TIMESTAMP NOT NULL,
    UPDATED_AT              TIMESTAMP,
    SENT_AT                 TIMESTAMP,
    CONSTRAINT UQ_SETTLE_BKLV_EXT_REF UNIQUE (EXT_REF)
);

COMMENT ON TABLE SETTLE_BKLV IS 'Bakong Large Value fund transfer settlement records';
COMMENT ON COLUMN SETTLE_BKLV.EXT_REF IS 'External reference for idempotency';
COMMENT ON COLUMN SETTLE_BKLV.ISO_MESSAGE IS 'ISO 20022 pain.001 XML message from the calling bank';
COMMENT ON COLUMN SETTLE_BKLV.BKLV_REQUEST_CONTENT IS 'Full SOAP request sent to BKLV';
COMMENT ON COLUMN SETTLE_BKLV.BKLV_RESPONSE_CONTENT IS 'Full SOAP response received from BKLV';
